# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alpa.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from H import Ui_H
from He import Ui_He
from Li import Ui_Li
from Be import Ui_Be
from B import Ui_B
from C import Ui_C
from N import Ui_N
from O import Ui_O
from F import Ui_F
from Ne import Ui_Ne
from Na import Ui_Na
from Mg import Ui_Mg
from Al import Ui_Al
from Si import Ui_Si
from P import Ui_P
from S import Ui_S
from Cl import Ui_Cl
from Ar import Ui_Ar
from K import Ui_K
from Ca import Ui_Ca
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import os

class Ui_Table(object):
    def H(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_H()
        self.ui.setupUi(self.window)
        self.window.show()
    def He(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_He()
        self.ui.setupUi(self.window)
        self.window.show()
    def Li(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Li()
        self.ui.setupUi(self.window)
        self.window.show()
    def Be(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Be()
        self.ui.setupUi(self.window)
        self.window.show()
    def B(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_B()
        self.ui.setupUi(self.window)
        self.window.show()
    def C(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_C()
        self.ui.setupUi(self.window)
        self.window.show()
    def N(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_N()
        self.ui.setupUi(self.window)
        self.window.show()
    def O(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_O()
        self.ui.setupUi(self.window)
        self.window.show()
    def F(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_F()
        self.ui.setupUi(self.window)
        self.window.show()
    def Ne(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Ne()
        self.ui.setupUi(self.window)
        self.window.show()
    def Na(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Na()
        self.ui.setupUi(self.window)
        self.window.show()
    def Mg(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Mg()
        self.ui.setupUi(self.window)
        self.window.show()
    def Al(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Al()
        self.ui.setupUi(self.window)
        self.window.show()
    def Si(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Si()
        self.ui.setupUi(self.window)
        self.window.show()
    def P(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_P()
        self.ui.setupUi(self.window)
        self.window.show()
    def S(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_S()
        self.ui.setupUi(self.window)
        self.window.show()
    def Cl(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Cl()
        self.ui.setupUi(self.window)
        self.window.show()
    def Ar(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Ar()
        self.ui.setupUi(self.window)
        self.window.show()
    def K(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_K()
        self.ui.setupUi(self.window)
        self.window.show()
    def Ca(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Ca()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, Table):
        Table.setObjectName("Table")
        Table.setFixedSize(791, 461)
        Table.setStyleSheet("background: rgb(74, 129, 124)")
        self.centralwidget = QtWidgets.QWidget(Table)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 40, 61, 61))
        self.pushButton.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.H)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(710, 40, 61, 61))
        self.pushButton_2.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.He)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 140, 61, 61))
        self.pushButton_3.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.Li)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 140, 61, 61))
        self.pushButton_4.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.Be)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(260, 140, 61, 61))
        self.pushButton_5.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.B)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(350, 140, 61, 61))
        self.pushButton_6.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.C)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(440, 140, 61, 61))
        self.pushButton_7.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.N)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(530, 140, 61, 61))
        self.pushButton_8.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.O)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(620, 140, 61, 61))
        self.pushButton_9.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(self.F)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(710, 140, 61, 61))
        self.pushButton_10.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(self.Ne)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(40, 250, 61, 61))
        self.pushButton_11.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.clicked.connect(self.Na)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(120, 250, 61, 61))
        self.pushButton_12.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.clicked.connect(self.Mg)
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(260, 250, 61, 61))
        self.pushButton_13.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.clicked.connect(self.Al)
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(350, 250, 61, 61))
        self.pushButton_14.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.clicked.connect(self.Si)
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(440, 250, 61, 61))
        self.pushButton_15.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_15.clicked.connect(self.P)
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(530, 250, 61, 61))
        self.pushButton_16.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_16.clicked.connect(self.S)
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(620, 250, 61, 61))
        self.pushButton_17.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_17.clicked.connect(self.Cl)
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(710, 250, 61, 61))
        self.pushButton_18.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_18.clicked.connect(self.Ar)
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(40, 360, 61, 61))
        self.pushButton_19.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_19.clicked.connect(self.K)
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(120, 360, 61, 61))
        self.pushButton_20.setStyleSheet("background: rgb(255, 255, 255)")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_20.clicked.connect(self.Ca)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 11, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background: rgb(85, 170, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(710, 11, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 111, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 111, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(260, 111, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(350, 111, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(440, 111, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(530, 111, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(620, 111, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(710, 111, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(40, 221, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(120, 221, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(260, 221, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(350, 221, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(440, 221, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(530, 221, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(620, 221, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(710, 221, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(40, 331, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(120, 331, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background: rgb(85, 170, 255)")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(250, 1, 441, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(510, 400, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        self.pushButton_15.raise_()
        self.pushButton_16.raise_()
        self.pushButton_17.raise_()
        self.pushButton_18.raise_()
        self.pushButton_20.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.pushButton_19.raise_()
        self.label_22.raise_()
        Table.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Table)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 25))
        self.menubar.setObjectName("menubar")
        Table.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Table)
        self.statusbar.setObjectName("statusbar")
        Table.setStatusBar(self.statusbar)

        self.retranslateUi(Table)
        QtCore.QMetaObject.connectSlotsByName(Table)

    def retranslateUi(self, Table):
        _translate = QtCore.QCoreApplication.translate
        Table.setWindowTitle(_translate("Table", "Table"))
        self.pushButton.setText(_translate("Table", "H\n"
"수소"))
        self.pushButton_2.setText(_translate("Table", "He \n"
"헬륨"))
        self.pushButton_3.setText(_translate("Table", "Li \n"
"리튬"))
        self.pushButton_4.setText(_translate("Table", "Be \n"
"베릴륨"))
        self.pushButton_5.setText(_translate("Table", "B \n"
"붕소"))
        self.pushButton_6.setText(_translate("Table", "C \n"
"탄소"))
        self.pushButton_7.setText(_translate("Table", "N \n"
"질소"))
        self.pushButton_8.setText(_translate("Table", "O \n"
"산소"))
        self.pushButton_9.setText(_translate("Table", "F \n"
"플루오린"))
        self.pushButton_10.setText(_translate("Table", "Ne \n"
"네온"))
        self.pushButton_11.setText(_translate("Table", "Na \n"
"나트륨"))
        self.pushButton_12.setText(_translate("Table", "Mg \n"
"마그네슘"))
        self.pushButton_13.setText(_translate("Table", "Al\n"
"알루미늄"))
        self.pushButton_14.setText(_translate("Table", "Si\n"
"규소"))
        self.pushButton_15.setText(_translate("Table", "P\n"
"인"))
        self.pushButton_16.setText(_translate("Table", "S\n"
"황"))
        self.pushButton_17.setText(_translate("Table", "Cl\n"
"염소"))
        self.pushButton_18.setText(_translate("Table", "Ar\n"
"아르곤"))
        self.pushButton_19.setText(_translate("Table", "K\n"
"칼륨"))
        self.pushButton_20.setText(_translate("Table", "Ca\n"
"칼슘"))
        self.label.setText(_translate("Table", "<html><head/><body><p align=\"center\">1</p></body></html>"))
        self.label_2.setText(_translate("Table", "<html><head/><body><p align=\"center\">2</p></body></html>"))
        self.label_3.setText(_translate("Table", "<html><head/><body><p align=\"center\">3</p></body></html>"))
        self.label_4.setText(_translate("Table", "<html><head/><body><p align=\"center\">4</p></body></html>"))
        self.label_5.setText(_translate("Table", "<html><head/><body><p align=\"center\">5</p></body></html>"))
        self.label_6.setText(_translate("Table", "<html><head/><body><p align=\"center\">6</p></body></html>"))
        self.label_7.setText(_translate("Table", "<html><head/><body><p align=\"center\">7</p></body></html>"))
        self.label_8.setText(_translate("Table", "<html><head/><body><p align=\"center\">8</p></body></html>"))
        self.label_9.setText(_translate("Table", "<html><head/><body><p align=\"center\">9</p></body></html>"))
        self.label_10.setText(_translate("Table", "<html><head/><body><p align=\"center\">10</p></body></html>"))
        self.label_11.setText(_translate("Table", "<html><head/><body><p align=\"center\">11</p></body></html>"))
        self.label_12.setText(_translate("Table", "<html><head/><body><p align=\"center\">12</p></body></html>"))
        self.label_13.setText(_translate("Table", "<html><head/><body><p align=\"center\">13</p></body></html>"))
        self.label_14.setText(_translate("Table", "<html><head/><body><p align=\"center\">14</p></body></html>"))
        self.label_15.setText(_translate("Table", "<html><head/><body><p align=\"center\">15</p></body></html>"))
        self.label_16.setText(_translate("Table", "<html><head/><body><p align=\"center\">16</p></body></html>"))
        self.label_17.setText(_translate("Table", "<html><head/><body><p align=\"center\">17</p></body></html>"))
        self.label_18.setText(_translate("Table", "<html><head/><body><p align=\"center\">18</p></body></html>"))
        self.label_19.setText(_translate("Table", "<html><head/><body><p align=\"center\">19</p></body></html>"))
        self.label_20.setText(_translate("Table", "<html><head/><body><p align=\"center\">20</p></body></html>"))
        self.label_21.setText(_translate("Table", "Periodic Table"))
        self.label_22.setText(_translate("Table", "-Only 20 elements are added"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Table = QtWidgets.QMainWindow()
    ui = Ui_Table()
    ui.setupUi(Table)
    Table.show()
    sys.exit(app.exec_())
